/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/e-xodim/departments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["EXodimController_getalldept"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["change-password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_getAll"];
    put?: never;
    post: operations["UsersController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["UsersController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profile/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["RolesController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/roles/getAllPermissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["RolesController_getAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/roles/{id}/permissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["RolesController_addPermissionsToRole"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/objects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ObjectsController_findAll"];
    put?: never;
    post: operations["ObjectsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/objects/{id}/values": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ObjectsController_addValue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/objects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ObjectsController_findOne"];
    put?: never;
    post?: never;
    delete: operations["ObjectsController_remove"];
    options?: never;
    head?: never;
    patch: operations["ObjectsController_update"];
    trace?: never;
  };
  "/api/v1/objects/values/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["ObjectsController_updateValue"];
    trace?: never;
  };
  "/api/v1/objects/project/{id}/employee/assign": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ObjectsController_assignEmployee"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/objects/project/{id}/employee/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ObjectsController_listEmployee"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/objects/project/{id}/employee/remove": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["ObjectsController_removeEmployee"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/infrastructure": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all infrastructure records */
    get: operations["getAllInfrastructure"];
    put?: never;
    /** Create a new infrastructure */
    post: operations["createInfrastructure"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/infrastructure/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get infrastructure by ID */
    get: operations["getInfrastructureById"];
    put?: never;
    post?: never;
    /** Delete infrastructure by ID */
    delete: operations["deleteInfrastructure"];
    options?: never;
    head?: never;
    /** Update infrastructure by ID */
    patch: operations["updateInfrastructure"];
    trace?: never;
  };
  "/api/v1/constructors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ConstructorsController_findAll"];
    put?: never;
    post: operations["ConstructorsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/constructors/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ConstructorsController_findOne"];
    put?: never;
    post?: never;
    delete: operations["ConstructorsController_remove"];
    options?: never;
    head?: never;
    patch: operations["ConstructorsController_update"];
    trace?: never;
  };
  "/api/v1/work-type": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["WorkTypeController_findAll"];
    put?: never;
    post: operations["WorkTypeController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/work-type/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["WorkTypeController_findOne"];
    put?: never;
    post?: never;
    delete: operations["WorkTypeController_remove"];
    options?: never;
    head?: never;
    patch: operations["WorkTypeController_update"];
    trace?: never;
  };
  "/api/v1/work": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["WorkController_createWork"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/work/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["WorkController_getAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/smeta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SmetaController_findAll"];
    put?: never;
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/smeta/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SmetaController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/smeta/{id}/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["SmetaController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/smeta/{id}/update": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["SmetaController_update"];
    trace?: never;
  };
  "/api/v1/measurements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["MeasurementsController_findAll"];
    put?: never;
    post: operations["MeasurementsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/measurements/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["MeasurementsController_findOne"];
    put?: never;
    post?: never;
    delete: operations["MeasurementsController_remove"];
    options?: never;
    head?: never;
    patch: operations["MeasurementsController_update"];
    trace?: never;
  };
  "/api/v1/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DocumentController_findAll"];
    put?: never;
    post: operations["DocumentController_createDocument"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DocumentController_searchWagonNumber"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PlotController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plot/totalEmployees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PlotController_getTotalEmployees"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plot/stat/groupByEmployees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PlotController_getGroupByEmployees"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plot/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PlotController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plot/{id}/employees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PlotController_getEmployeesFromIntegration"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plot/addEmployees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PlotController_addEmployeesToPlot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/storage/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["StorageController_uploadFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      username: string;
      password: string;
    };
    ChangePasswordDto: {
      oldPassword: string;
      newPassword: string;
    };
    CreateUserDto: {
      username: string;
      password: string;
    };
    CreateRoleDto: {
      name: string;
    };
    CreatePermissionDto: {
      name: string;
    };
    AddPermissionsDto: {
      permissionNames: components["schemas"]["CreatePermissionDto"][];
    };
    CreateProjectObjectDto: {
      lat: string;
      lng: string;
      /** @enum {string} */
      status: "new" | "in_progress" | "completed" | "canceled";
      constructionPeriod: string;
      masterProject: string;
      customer: string;
      pudaratOrganization: string;
      lengthObject: string;
      objectValue: string;
      financingInfo: string;
      workDone: string;
      commissioningPeriod: string;
      fileIds?: string[];
    };
    CreateStationDto: Record<string, never>;
    ReponseProjectObjectDto: {
      id: string;
      lat: string;
      lng: string;
      /** @enum {string} */
      status: "new" | "in_progress" | "completed" | "canceled";
      constructionPeriod: string;
      masterProject: string;
      customer: string;
      pudaratOrganization: string;
      lengthObject: string;
      objectValue: string;
      financingInfo: string;
      workDone: string;
      commissioningPeriod: string;
      fileIds?: components["schemas"]["CreateStationDto"];
    };
    ApiResponseReponseProjectObjectDto: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.552Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      data?: components["schemas"]["ReponseProjectObjectDto"];
    };
    CreateValueDto: {
      name: string;
      value: string;
    };
    ApiResponseCreateValueDto: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.551Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      data?: components["schemas"]["CreateValueDto"];
    };
    Object: Record<string, never>;
    ApiResponseReponseProjectObjectDtoArray: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.552Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      data?: components["schemas"]["ReponseProjectObjectDto"][];
    };
    UpdateProjectObjectDto: Record<string, never>;
    UpdateValueDto: Record<string, never>;
    AssignEmployeeDto: {
      pin: string;
    };
    RemoveEmployeeDto: {
      id: string;
      ids: string[];
    };
    CreateInfrastructureDto: {
      struct: string;
      code: string;
      xId: string;
    };
    ApiResponseCreateInfrastructureDto: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.727Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      data?: components["schemas"]["CreateInfrastructureDto"];
    };
    UpdateInfrastructureDto: Record<string, never>;
    LangDto: {
      uz: string;
      en: string;
      ru: string;
      kril: string;
    };
    DynamicFieldDto: {
      key: components["schemas"]["LangDto"];
      value: components["schemas"]["LangDto"];
    };
    CreateConstructorDto: {
      fields: components["schemas"]["DynamicFieldDto"][];
    };
    UpdateConstructorDto: Record<string, never>;
    CreateWorkTypeDto: {
      name: string;
    };
    UpdateWorkTypeDto: Record<string, never>;
    CreateWorkDto: {
      name: string;
      workTypeId: string;
      currentPlan: string;
      workDoneOnTheFact: string;
    };
    CreateSmetaDto: {
      /**
       * @description Unique code for the smeta
       * @example SMT-001
       */
      code: string;
      /**
       * @description Constructor identifier (optional)
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      constructorId?: string;
      /**
       * @description ProjectObject ID
       * @example f84c48f9-3b8f-4de3-a9fd-10e83ec5ac12
       */
      projectId: string;
      /**
       * @description Infrastructure ID
       * @example 42c5a9e7-7f6c-4a99-9f88-5dbfa5fbc5c2
       */
      infraId: string;
      /**
       * @description File ID from StorageEntity (optional)
       * @example f0d3a1b9-9c4d-47ff-b2f8-28f3b2a32222
       */
      fileId?: string;
    };
    ApiResponseCreateSmetaDto: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.724Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      data?: components["schemas"]["CreateSmetaDto"];
    };
    CreateMeasurementDto: Record<string, never>;
    UpdateMeasurementDto: Record<string, never>;
    CreateDocumentDto: {
      name: string;
      fileId: string;
      status: boolean;
    };
    ApiResponseCreateDocumentDto: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.692Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      data?: components["schemas"]["CreateDocumentDto"];
    };
    DocumentResponseDto: {
      id: string;
      title: string;
      description: string;
      /** Format: date-time */
      createdAt: string;
    };
    ApiResponseDocumentResponseDto: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.692Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      data?: components["schemas"]["DocumentResponseDto"];
    };
    ApiResponseDocumentResponseDtoArray: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.692Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      data?: components["schemas"]["DocumentResponseDto"][];
    };
    CreateEmployeeDto: {
      employeeId: string;
    };
    CreatePlotDto: {
      name: string;
      employees: components["schemas"]["CreateEmployeeDto"][];
    };
    AddEmployeesToPlotDto: {
      plotId: string;
      employees: components["schemas"]["CreateEmployeeDto"][];
    };
    ApiResponseObject: {
      /** @example true */
      success: boolean;
      /** @example 200 */
      statusCode: number;
      /** @example 2025-09-18T10:42:43.687Z */
      timestamp: string;
      /** @example /api/example */
      path: string;
      /** @example GET */
      method: string;
      /** @example FETCHED SUCCESSFULLY */
      message: string;
      /** @example {
       *       "id": "uuid-or-number"
       *     } */
      data?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  EXodimController_getalldept: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_getAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RolesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRoleDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RolesController_getAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RolesController_addPermissionsToRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddPermissionsDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ObjectsController_findAll: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        /** @description Filter conditions */
        where?: components["schemas"]["Object"];
        /** @description Order by fields */
        order?: components["schemas"]["Object"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseReponseProjectObjectDtoArray"];
        };
      };
    };
  };
  ObjectsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProjectObjectDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseReponseProjectObjectDto"];
        };
      };
    };
  };
  ObjectsController_addValue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateValueDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseCreateValueDto"];
        };
      };
    };
  };
  ObjectsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseReponseProjectObjectDto"];
        };
      };
    };
  };
  ObjectsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseReponseProjectObjectDto"];
        };
      };
    };
  };
  ObjectsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectObjectDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseReponseProjectObjectDto"];
        };
      };
    };
  };
  ObjectsController_updateValue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateValueDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseCreateValueDto"];
        };
      };
    };
  };
  ObjectsController_assignEmployee: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignEmployeeDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseReponseProjectObjectDto"];
        };
      };
    };
  };
  ObjectsController_listEmployee: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseReponseProjectObjectDtoArray"];
        };
      };
    };
  };
  ObjectsController_removeEmployee: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveEmployeeDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseReponseProjectObjectDto"];
        };
      };
    };
  };
  getAllInfrastructure: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of infrastructure */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateInfrastructureDto"][];
        };
      };
    };
  };
  createInfrastructure: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInfrastructureDto"];
      };
    };
    responses: {
      /** @description Infrastructure created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseCreateInfrastructureDto"];
        };
      };
    };
  };
  getInfrastructureById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Infrastructure ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Infrastructure found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateInfrastructureDto"];
        };
      };
      /** @description Infrastructure not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteInfrastructure: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Infrastructure ID */
        id: components["schemas"]["CreateInfrastructureDto"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Infrastructure deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Infrastructure not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateInfrastructure: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Infrastructure ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateInfrastructureDto"];
      };
    };
    responses: {
      /** @description Infrastructure updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateInfrastructureDto"];
        };
      };
      /** @description Infrastructure not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ConstructorsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ConstructorsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateConstructorDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ConstructorsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ConstructorsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ConstructorsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateConstructorDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkTypeController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkTypeController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkTypeDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkTypeController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkTypeController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkTypeController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorkTypeDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkController_createWork: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkController_getAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SmetaController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSmetaDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseCreateSmetaDto"];
        };
      };
    };
  };
  SmetaController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SmetaController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SmetaController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MeasurementsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MeasurementsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMeasurementDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MeasurementsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MeasurementsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MeasurementsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMeasurementDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DocumentController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseDocumentResponseDtoArray"];
        };
      };
    };
  };
  DocumentController_createDocument: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDocumentDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseCreateDocumentDto"];
        };
      };
    };
  };
  DocumentController_searchWagonNumber: {
    parameters: {
      query: {
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseDocumentResponseDto"];
        };
      };
    };
  };
  PlotController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePlotDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlotController_getTotalEmployees: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlotController_getGroupByEmployees: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlotController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlotController_getEmployeesFromIntegration: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlotController_addEmployeesToPlot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddEmployeesToPlotDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  StorageController_uploadFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @description File to upload
           */
          file?: string;
        };
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseObject"];
        };
      };
    };
  };
}
